# Configuration of 2 CentOS machines to test HA configuration.
# Marcelo Garcia (marcelomgarcia@gmail.com)

- hosts: nodes
  # Privilege escalation
  become: true
  become_method: sudo
  # Disable selinux
  tasks:
  - name: disable SElinux.
    selinux:
      state: disabled
  - name: Extra packages including corosync and pacemaker.
    action: yum name={{ item }} state=present update_cache=yes
    with_items: 
      - redhat-lsb
      - vim
      - curl 
      - pacemaker 
      - pcs
      - resource-agents
  # TODO: create/add lines to /etc/hosts via templates.
  - name: Add flik to /etc/hosts.
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.10'
      line: '192.168.50.10   flik'
      owner: root
      group: root
      mode: 0644
  - name: Atta to /etc/hosts
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.11'
      line: '192.168.50.11   atta'
      owner: root
      group: root
      mode: 0644
  # start the services
  - name: Start pcsd service.
    service:
      name: pcsd
      state: started
  - name: Enable pcsd service. 
    service:
      name: pcsd
      enabled: yes