# Configuration of 2 CentOS machines to test HA configuration.
# Marcelo Garcia (marcelomgarcia@gmail.com)

- hosts: all
  # Privilege escalation
  become: true
  become_method: sudo
  # Disable selinux
  tasks:
  - name: disable SElinux.
    selinux:
      state: disabled
  - name: Install basic packages.
    action: yum name={{ item }} state=present update_cache=yes
    with_items: 
      - redhat-lsb
      - vim
      - curl 
  - name: Add flik to /etc/hosts.
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.10'
      line: '192.168.50.10   flik'
      owner: root
      group: root
      mode: 0644
  - name: Atta to /etc/hosts
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.11'
      line: '192.168.50.11   atta'
      owner: root
      group: root
      mode: 0644      