# Configuration of 2 CentOS machines to test HA configuration.
# Marcelo Garcia (marcelomgarcia@gmail.com)

- hosts: nodes
  # Privilege escalation
  become: true
  become_method: sudo
  # Disable selinux
  tasks:
  - name: disable SElinux.
    selinux:
      state: disabled
  - name: Extra packages including corosync and pacemaker.
    action: yum name={{ item }} state=present update_cache=yes
    with_items: 
      - redhat-lsb
      - vim
      - curl 
      - pacemaker 
      - pcs
      - resource-agents
  # TODO: create/add lines to /etc/hosts via templates.
  - name: Add flik to /etc/hosts.
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.10'
      line: '192.168.50.10   flik'
      owner: root
      group: root
      mode: 0644
  - name: Atta to /etc/hosts
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.11'
      line: '192.168.50.11   atta'
      owner: root
      group: root
      mode: 0644
  # start the services
  - name: Start pcsd service.
    service:
      name: pcsd
      state: started
  - name: Enable pcsd service. 
    service:
      name: pcsd
      enabled: yes
  # Creating ssh keys for root.
  - name: Generating ssh keys for root.
    command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    args: 
      creates: /root/.ssh/id_rsa
    become: yes
  # TODO. Find a way to create the authorized_keys so they can ssh
  # to each other without password. END TODO.
  # Authorization for 'pcs'.
  - name: Pcs authorization.
    command: echo CHANGEME | passwd --stdin hacluster
    become: yes
    become_method: su
- hosts: flik
  become: yes
  tasks: 
  - name: Finishing authorization for 'pcs'.
    command: pcs cluster auth flik atta -u hacluster -p CHANGEME --force