# Configuration of 2 CentOS machines to test HA configuration.
# Marcelo Garcia (marcelomgarcia@gmail.com)

- hosts: nodes
  # Privilege escalation
  become: true
  become_method: sudo
  # Disable selinux
  tasks:
  - name: disable SElinux.
    selinux:
      state: disabled
  - name: Extra packages including corosync and pacemaker.
    action: yum name={{ item }} state=present update_cache=yes
    with_items: 
      - redhat-lsb
      - vim
      - curl 
      - pacemaker 
      - pcs
      - resource-agents
  # TODO: create/add lines to /etc/hosts via templates.
  - name: Add flik to /etc/hosts.
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.10'
      line: '192.168.50.10   flik'
      owner: root
      group: root
      mode: 0644
  - name: Atta to /etc/hosts
    lineinfile: 
      path: /etc/hosts
      regexp: '^192\.168\.50\.11'
      line: '192.168.50.11   atta'
      owner: root
      group: root
      mode: 0644
  # Copy the configuration file.
  - name: Copy 'corosync.conf' file.
    copy:
      src: files/corosync.conf
      dest: /etc/corosync/
      owner: root
      group: root
      mode: 0644
  # start the services
  - name: Start pcsd service.
    service:
      name: pcsd
      state: started
  - name: Enable pcsd service. 
    service:
      name: pcsd
      enabled: yes
  # Create the '/root/.ssh' directory.
  - name: Create root's ssh directory.
    file: 
      path: /root/.ssh
      state: directory
      mode: 0700
  # Import 'ssh' keys
  - name: Copy ssh authorized_keys file.
    copy:
      src: files/ssh_keys/authorized_keys
      dest: /root/.ssh/
      owner: root
      group: root
      mode: 0644
  - name: Copy private key.
    copy:
      src: files/ssh_keys/id_rsa
      dest: /root/.ssh/
      owner: root
      group: root
      mode: 0600
  - name: Copy public key.
    copy:
      src: files/ssh_keys/id_rsa.pub
      dest: /root/.ssh/
      owner: root
      group: root
      mode: 0644
  - name: Copy ssh config file to root's ssh dir.
    copy:
      src: files/ssh_keys/config
      dest: /root/.ssh/
      owner: root
      group: root
      mode: 0400
  # Authorization for 'pcs'.
  - name: Pcs authorization.
    shell: echo CHANGEME | passwd --stdin hacluster
- hosts: flik
  become: yes
  become_method: sudo
  tasks: 
  - name: Authentication for 'pcs'.
    shell: pcs cluster auth flik atta -u hacluster -p CHANGEME --force
  - name: Start the cluster on atta
    shell: pcs cluster start atta
  - name: Start the cluster on flik
    shell: pcs cluster start